nodeLinker: node-modules
# This sets up the workspace feature, making Yarn aware of the sub-projects (packages) in your monorepo
# workspaces:
#   packages:
#     - ui
#     - server
# # This enables strict mode, which ensures Yarn enforces the declared package structure
# # and helps catch issues early.
# strictSsl: true

# # Plug'n'Play settings
# pnpMode: strict

# # Enable checksum validation
# enableStrictChecksums: true

# # Enable the global cache folder
# globalFolder: ~/.yarn/global

# # Specifies the location of the Yarn cache
# cacheFolder: ./.yarn/cache

# # Enable immutable installs
# enableImmutableInstalls: true

# # Enable verbose logs
# enableInlineBuilds: false

# # Telemetry settings
# enableTelemetry: false

# # Configure yarn to automatically prune dependencies on install
# nmMode: hardlinks-local
